/* Controlled fixture: only modifies its own test DLL/data. Never executes the
   generated bytes or the redirected import. stdin protocol is used by tests. */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

static uint64_t *find_tick_slot(HMODULE dll){
    uint8_t *base=(uint8_t *)(uintptr_t)dll;
    IMAGE_DOS_HEADER *dos=(IMAGE_DOS_HEADER *)base;
    IMAGE_NT_HEADERS64 *nt=(IMAGE_NT_HEADERS64 *)(base+dos->e_lfanew);
    IMAGE_IMPORT_DESCRIPTOR *desc=(IMAGE_IMPORT_DESCRIPTOR *)(base+nt->OptionalHeader.DataDirectory[1].VirtualAddress);
    for(;desc->Name;++desc){
        IMAGE_THUNK_DATA64 *names,*slots;
        if(!desc->OriginalFirstThunk){ continue; }
        names=(IMAGE_THUNK_DATA64 *)(base+desc->OriginalFirstThunk);
        slots=(IMAGE_THUNK_DATA64 *)(base+desc->FirstThunk);
        for(;names->u1.AddressOfData;++names,++slots){
            if(!(names->u1.Ordinal&IMAGE_ORDINAL_FLAG64)){
                IMAGE_IMPORT_BY_NAME *name=(IMAGE_IMPORT_BY_NAME *)(base+names->u1.AddressOfData);
                if(!strcmp((const char *)name->Name,"GetTickCount")){ return &slots->u1.Function; }
            }
        }
    }
    return NULL;
}
int wmain(int argc,wchar_t **argv){
    HMODULE dll;
    FARPROC symbol;
    uint8_t *block=NULL,*private_memory;
    uint8_t original[12],patch[12]={0x48,0xb8,0,0,0,0,0,0,0,0,0xff,0xe0};
    uint64_t *iat,original_iat;
    DWORD saved,discard;
    char command[32];
    if(argc!=2){ fputs("Usage: demo_host.exe ABSOLUTE_PATH_TO_DLL\n",stderr);return 2; }
    dll=LoadLibraryExW(argv[1],NULL,LOAD_LIBRARY_SEARCH_DLL_LOAD_DIR|LOAD_LIBRARY_SEARCH_DEFAULT_DIRS);
    if(!dll){ fprintf(stderr,"LoadLibrary failed: %lu\n",(unsigned long)GetLastError());return 1; }
    symbol=GetProcAddress(dll,"ps_demo_block");memcpy(&block,&symbol,sizeof(block));
    if(!block){ fprintf(stderr,"GetProcAddress(ps_demo_block) failed: %lu\n",(unsigned long)GetLastError());return 1; }
    iat=find_tick_slot(dll);
    if(!iat){ fputs("GetTickCount import missing from the test DLL. Rebuild demo_module as x64.\n",stderr);return 1; }
    block+=sizeof(void *);memcpy(original,block,sizeof(original));original_iat=*iat;
    private_memory=(uint8_t *)VirtualAlloc(NULL,4096,MEM_RESERVE|MEM_COMMIT,PAGE_READWRITE);
    if(!private_memory){ fprintf(stderr,"VirtualAlloc failed: %lu\n",(unsigned long)GetLastError());return 1; }
    printf("{\"pid\":%lu,\"base\":\"0x%llx\",\"patch\":\"0x%llx\",\"iat\":\"0x%llx\",\"private\":\"0x%llx\"}\n",
           (unsigned long)GetCurrentProcessId(),(unsigned long long)(uintptr_t)dll,
           (unsigned long long)(uintptr_t)block,(unsigned long long)(uintptr_t)iat,
           (unsigned long long)(uintptr_t)private_memory);fflush(stdout);
    while(fgets(command,sizeof(command),stdin)){
        if(!strncmp(command,"patch",5)){
            uint64_t target=(uint64_t)(uintptr_t)private_memory;
            memcpy(patch+2,&target,sizeof(target));
            private_memory[0]='M';private_memory[1]='Z';private_memory[60]=0x80;
            memcpy(private_memory+0x80,"PE\0\0",4);
            if(!VirtualProtect(private_memory,4096,PAGE_EXECUTE_READ,&discard) ||
               !VirtualProtect(block,12,PAGE_READWRITE,&saved)){ return 1; }
            memcpy(block,patch,12);
            if(!VirtualProtect(block,12,saved,&discard)){ return 1; }
            FlushInstructionCache(GetCurrentProcess(),block,12);
        }else if(!strncmp(command,"iat",3)){
            if(!VirtualProtect(iat,8,PAGE_READWRITE,&saved)){ return 1; }
            *iat=(uint64_t)(uintptr_t)private_memory;
            if(!VirtualProtect(iat,8,saved,&discard)){ return 1; }
        }else if(!strncmp(command,"noaccess",8)){
            if(!VirtualProtect(block,12,PAGE_NOACCESS,&saved)){ return 1; }
        }else if(!strncmp(command,"restore",7)){
            if(!VirtualProtect(block,12,PAGE_READWRITE,&discard)){ return 1; }
            memcpy(block,original,12);
            if(!VirtualProtect(block,12,PAGE_EXECUTE_READ,&discard) ||
               !VirtualProtect(iat,8,PAGE_READWRITE,&saved)){ return 1; }
            *iat=original_iat;
            if(!VirtualProtect(iat,8,saved,&discard) ||
               !VirtualProtect(private_memory,4096,PAGE_READWRITE,&discard)){ return 1; }
            memset(private_memory,0,4096);FlushInstructionCache(GetCurrentProcess(),block,12);
        }else if(!strncmp(command,"quit",4)){ break; }
        else{ puts("unknown");fflush(stdout);continue; }
        puts("ok");fflush(stdout);
    }
    /* Exit without executing altered test bytes or the redirected DLL import. */
    ExitProcess(0);
}
