"""Regenerate the C report template; normal builds use the committed header."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def main():
    source = (ROOT / 'assets/report.html').read_text(encoding='utf-8')
    head, tail = source.split('<!-- REPORT_DATA -->')
    output = ['/* Generated by tools/embed_ui.py from assets/report.html. */']
    for name, text in (('head', head), ('tail', tail)):
        output.append(f'static const char *const ps_html_{name}[]={{')
        output.extend(json.dumps(text[i:i + 1800], ensure_ascii=True) + ',' for i in range(0, len(text), 1800))
        output.extend(['NULL', '};'])
    (ROOT / 'src/ui.h').write_text('\n'.join(output) + '\n', encoding='ascii')


if __name__ == '__main__': main()
